amt=int(input("Enter the amount: "))
mon=(amt//500)
rem=(amt%500)
mone=(rem//100)
rema=(rem%100)
money=(rema//50)
remai=(rema%50)
moneyy=(remai//20)
remain=(remai%20)
moneyyy=(remain//10)
remaind=(remain%10)
print("The number of 500 notes:", mon)
print("The number of 100 notes:", mone)
print("The number of 50 notes:", money)
print("The number of 20 notes:", moneyy)
print("The number of 10 notes:", moneyyy)
print("The number of 1 notes:", remaind)
